-- =============================================================================
-- Tender Intelligence System — Supabase Schema
-- CBA Benelux | ManageEngine | Dutch Public Procurement
-- Run this in Supabase SQL Editor to initialize all tables and indexes
-- =============================================================================

-- ---------------------------------------------------------------------------
-- TABLE: tenders
-- Central record for every tender detected across all sources
-- ---------------------------------------------------------------------------
CREATE TABLE tenders (
  id                        UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  external_id               TEXT UNIQUE NOT NULL,         -- TenderNed ID or TED notice ID
  ted_reference             TEXT,                         -- cross-platform dedup key (from TNS tedPublicatieReferentie)
  source                    TEXT NOT NULL,                -- 'TenderNed_RSS' | 'TNS_API' | 'TED'

  -- Core tender fields
  title                     TEXT,
  buyer                     TEXT,
  buyer_type                TEXT,                         -- 'gemeente' | 'rijks' | 'onderwijs' | 'zorg' | 'politie' | 'provincie' | 'water' | 'zbo' | 'overig'
  buyer_normalized          TEXT,                         -- lowercase stripped, for known_buyers lookup
  country                   TEXT DEFAULT 'NL',
  publication_date          TIMESTAMPTZ,
  deadline_submission       TIMESTAMPTZ,
  deadline_questions        TIMESTAMPTZ,
  procedure_type            TEXT,                         -- 'openbaar' | 'niet-openbaar' | 'onderhandeling' | 'versneld' | 'mini-competitie'
  cpv_codes                 TEXT[],
  cpv_primary               TEXT,
  estimated_value_eur       NUMERIC,
  estimated_value_disclosed BOOLEAN DEFAULT FALSE,
  publication_type          TEXT,                         -- 'aankondiging' | 'gunning' | 'correctie'
  url_tenderned             TEXT,
  url_ted                   TEXT,
  summary_raw               TEXT,                         -- raw description text from source
  document_links            JSONB,                        -- [{name, url, type}]

  -- Filter pipeline results
  cpv_filter_result         TEXT,                         -- 'PASS' | 'AMBIGUOUS' | 'DISQUALIFY' | 'NO_CPV'
  keyword_filter_result     TEXT,                         -- 'PASS' | 'AMBIGUOUS' | 'DISQUALIFY'
  keyword_matches           TEXT[],                       -- which keywords triggered PASS
  llm_classification        TEXT,                         -- 'RELEVANT' | 'NOT_RELEVANT' | 'SKIPPED'
  llm_classification_reason TEXT,

  -- Scoring
  score                     INTEGER,
  score_breakdown           JSONB,                        -- {dimension_name: points} for tuning
  label                     TEXT,                         -- 'Hot' | 'Warm' | 'Cold' | 'Monitor' | 'Disqualified'
  red_flags                 TEXT[],
  needs_rescore             BOOLEAN DEFAULT FALSE,
  processed                 BOOLEAN DEFAULT FALSE,
  processed_at              TIMESTAMPTZ,

  -- Intelligence (WF-C, generated by LLM after scoring)
  executive_summary         TEXT,
  what_is_being_bought      TEXT,
  why_it_matters            TEXT,
  recommended_products      TEXT[],
  product_fit_reasoning     TEXT,
  product_fit_level         TEXT,                         -- 'Strong' | 'Moderate' | 'Weak'
  competitive_context       TEXT,
  action_recommendation     TEXT,
  route_to_market           TEXT,
  route_reasoning           TEXT,
  llm_intelligence_run      BOOLEAN DEFAULT FALSE,
  intelligence_generated_at TIMESTAMPTZ,

  -- Tracking
  version                   INTEGER DEFAULT 1,
  included_in_digest_date   DATE,
  created_at                TIMESTAMPTZ DEFAULT NOW(),
  updated_at                TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for WF-B (filter loop) and WF-D (digest query)
CREATE INDEX idx_tenders_processed     ON tenders(processed)     WHERE processed = false;
CREATE INDEX idx_tenders_needs_rescore ON tenders(needs_rescore) WHERE needs_rescore = true;
CREATE INDEX idx_tenders_label         ON tenders(label);
CREATE INDEX idx_tenders_pub_date      ON tenders(publication_date DESC);
CREATE INDEX idx_tenders_external_id   ON tenders(external_id);
CREATE INDEX idx_tenders_deadline      ON tenders(deadline_submission) WHERE deadline_submission IS NOT NULL;

-- Auto-update updated_at on any row change
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER tenders_updated_at
  BEFORE UPDATE ON tenders
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();


-- ---------------------------------------------------------------------------
-- TABLE: tender_changes
-- Tracks NvI rounds, deadline changes, amendments, corrections
-- ---------------------------------------------------------------------------
CREATE TABLE tender_changes (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tender_id     UUID REFERENCES tenders(id) ON DELETE CASCADE,
  version       INTEGER,
  changed_field TEXT,
  old_value     TEXT,
  new_value     TEXT,
  change_type   TEXT,           -- 'nvi_round' | 'deadline_change' | 'value_change' | 'correction'
  detected_at   TIMESTAMPTZ DEFAULT NOW(),
  notified      BOOLEAN DEFAULT FALSE
);

CREATE INDEX idx_tender_changes_tender_id  ON tender_changes(tender_id);
CREATE INDEX idx_tender_changes_type       ON tender_changes(change_type);
CREATE INDEX idx_tender_changes_notified   ON tender_changes(notified) WHERE notified = false;


-- ---------------------------------------------------------------------------
-- TABLE: known_buyers
-- CBA customer/prospect lookup for Dimension 7 scoring
-- Populate manually or via CSV import after initial deployment
-- ---------------------------------------------------------------------------
CREATE TABLE known_buyers (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  buyer_normalized  TEXT UNIQUE,           -- lowercase stripped, matches tenders.buyer_normalized
  buyer_display     TEXT,
  relationship_type TEXT,                  -- 'existing_customer' | 'lost' | 'prospect' | 'competitor_account'
  notes             TEXT,
  last_updated      DATE
);


-- ---------------------------------------------------------------------------
-- TABLE: workflow_health
-- One row per workflow run — monitor for failures and empty fetches
-- ---------------------------------------------------------------------------
CREATE TABLE workflow_health (
  id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  workflow_name    TEXT,
  run_at           TIMESTAMPTZ DEFAULT NOW(),
  tenders_fetched  INTEGER DEFAULT 0,
  tenders_new      INTEGER DEFAULT 0,
  tenders_updated  INTEGER DEFAULT 0,
  errors           JSONB,
  duration_seconds INTEGER
);

CREATE INDEX idx_workflow_health_name ON workflow_health(workflow_name);
CREATE INDEX idx_workflow_health_run  ON workflow_health(run_at DESC);


-- ---------------------------------------------------------------------------
-- VIEWS: Operational dashboards (bookmark these in Supabase)
-- ---------------------------------------------------------------------------

-- Active pipeline: Hot and Warm tenders still open
CREATE VIEW v_active_pipeline AS
SELECT
  external_id, title, buyer, label, score,
  deadline_submission,
  recommended_products,
  action_recommendation,
  url_tenderned,
  publication_date,
  source
FROM tenders
WHERE label IN ('Hot', 'Warm')
  AND (deadline_submission IS NULL OR deadline_submission > NOW())
ORDER BY score DESC, deadline_submission ASC NULLS LAST;

-- Recent NvI alerts (last 7 days)
CREATE VIEW v_recent_nvi AS
SELECT
  t.title, t.buyer, t.label,
  tc.detected_at, tc.change_type,
  tc.old_value, tc.new_value
FROM tender_changes tc
JOIN tenders t ON t.id = tc.tender_id
WHERE tc.change_type = 'nvi_round'
  AND tc.detected_at >= NOW() - INTERVAL '7d'
ORDER BY tc.detected_at DESC;

-- Weekly review: Hot tenders last 7 days
CREATE VIEW v_weekly_hot AS
SELECT *
FROM tenders
WHERE label = 'Hot'
  AND publication_date >= NOW() - INTERVAL '7d'
ORDER BY score DESC;

-- Pipeline health: today's run stats
CREATE VIEW v_health_today AS
SELECT *
FROM workflow_health
WHERE run_at >= CURRENT_DATE
ORDER BY run_at DESC;
